import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('dify models/tools/datasets/agent API modules expose expected helpers', () => {
  const models = readFileSync(new URL('../../integrations/api/difyModelsApi.js', import.meta.url), 'utf8')
  const tools = readFileSync(new URL('../../integrations/api/difyToolsApi.js', import.meta.url), 'utf8')
  const datasets = readFileSync(new URL('../../datasets/api/difyDatasetsApi.js', import.meta.url), 'utf8')
  const agent = readFileSync(new URL('../api/difyAgentApi.js', import.meta.url), 'utf8')

  assert.match(models, /model-providers/)
  assert.match(models, /credentials\/validate/)
  assert.match(tools, /tools\/builtin/)
  assert.match(tools, /tool-provider\/builtin/)
  assert.match(tools, /credential\/schema/)
  assert.doesNotMatch(tools, /\/credentials_schema/)
  assert.match(tools, /encodeProviderPath/)
  assert.match(datasets, /\/datasets/)
  assert.match(datasets, /retrieval-setting/)
  assert.match(datasets, /createEmptyDataset|post\('\/datasets'/)
  assert.match(datasets, /\/datasets\/init/)
  assert.match(datasets, /indexing-status/)
  assert.match(datasets, /hit-testing/)
  assert.match(agent, /agent-composer/)
  assert.match(agent, /\/agent/)
})

test('model APIs use llm model type not text-generation', () => {
  const models = readFileSync(new URL('../../integrations/api/difyModelsApi.js', import.meta.url), 'utf8')
  const workflow = readFileSync(new URL('../api/difyWorkflowApi.js', import.meta.url), 'utf8')
  const store = readFileSync(new URL('../../integrations/state/useModelStore.js', import.meta.url), 'utf8')
  assert.match(models, /DEFAULT_LLM_MODEL_TYPE = 'llm'/)
  assert.match(workflow, /model-types\/llm/)
  assert.doesNotMatch(workflow, /model-types\/text-generation/)
  assert.match(store, /DEFAULT_LLM_MODEL_TYPE/)
  assert.doesNotMatch(store, /text-generation/)
})
test('knowledge retrieval config writes multiple_retrieval_config', () => {
  const source = readFileSync(new URL('../nodes/knowledge-retrieval/useKnowledgeRetrievalConfig.js', import.meta.url), 'utf8')
  assert.match(source, /multiple_retrieval_config/)
  assert.match(source, /retrieval_mode/)
  assert.match(source, /dataset_ids/)
})

test('http request config normalizes body to Dify shape', () => {
  const source = readFileSync(new URL('../nodes/http-request/useHttpRequestConfig.js', import.meta.url), 'utf8')
  const panel = readFileSync(new URL('../nodes/http-request/HttpRequestPanel.vue', import.meta.url), 'utf8')
  assert.match(source, /type = 'json'/)
  assert.match(source, /type = 'raw-text'/)
  assert.match(source, /type === 'none'/)
  assert.match(source, /convertHttpBody/)
  assert.match(source, /setHttpErrorStrategy/)
  assert.match(panel, /ErrorHandleConfig/)
  assert.match(panel, /form-data/)
  assert.match(panel, /binary/)
})

test('agent node default data uses agent-v2 binding shape', () => {
  const source = readFileSync(new URL('./nodeMeta.js', import.meta.url), 'utf8')
  assert.match(source, /agent_node_kind: 'dify_agent'/)
  assert.match(source, /binding_type: 'inline_agent'/)
  assert.match(source, /version: '2'/)
})

test('agent panel is v2-only and creates inline binding with node_job_only', () => {
  const panel = readFileSync(new URL('../nodes/t/AgentPanel.vue', import.meta.url), 'utf8')
  const binding = readFileSync(new URL('../nodes/t/agentBinding.js', import.meta.url), 'utf8')
  const node = readFileSync(new URL('../nodes/t/AgentNode.vue', import.meta.url), 'utf8')

  assert.doesNotMatch(panel, /经典策略/)
  assert.doesNotMatch(panel, /listAgentStrategies/)
  assert.match(panel, /ensureInlineBinding/)
  assert.match(panel, /buildCreateInlineBindingPayload/)
  assert.match(panel, /buildSaveComposerPayload/)
  assert.match(panel, /scheduleAutoSync/)
  assert.match(binding, /normalizeAgentV2NodeData/)
  assert.match(binding, /node_job_only/)
  assert.match(binding, /save_to_current_version/)
  assert.match(node, /bindingReady|hasValidAgentBinding/)
  assert.doesNotMatch(node, /agent_strategy_label/)
})

test('run path autosaves draft before execution', () => {
  const layout = readFileSync(new URL('../pages/WorkflowPage.vue', import.meta.url), 'utf8')
  assert.match(layout, /syncDraftBeforeRun/)
  assert.match(layout, /await syncDraftBeforeRun\(\)/)
})

test('model selector supports searchable filtering and provider icons', () => {
  const selector = readFileSync(new URL('../nodes/shared/ModelSelector.vue', import.meta.url), 'utf8')
  const icon = readFileSync(new URL('../nodes/base/ModelIcon.vue', import.meta.url), 'utf8')
  const store = readFileSync(new URL('../../integrations/state/useModelStore.js', import.meta.url), 'utf8')

  assert.match(selector, /filter-method/)
  assert.match(selector, /filteredProviders/)
  assert.match(selector, /ModelIcon/)
  assert.match(icon, /providerIconUrl|icon_small|iconUrl/)
  assert.match(store, /icon_small/)
  assert.match(store, /getProvider/)
})


test('integrations page routes models/tools tabs and top navigation entry exists', () => {
  const router = readFileSync(new URL('../../../app/router/index.js', import.meta.url), 'utf8')
  const navigation = readFileSync(new URL('../../../app/navigation.js', import.meta.url), 'utf8')
  const page = readFileSync(new URL('../../integrations/pages/Integrations.vue', import.meta.url), 'utf8')
  const toolsApi = readFileSync(new URL('../../integrations/api/difyToolsApi.js', import.meta.url), 'utf8')

  assert.match(router, /path: '\/integrations'/)
  assert.match(navigation, /to: '\/integrations'/)
  assert.match(navigation, /label: '模型与工具'/)
  assert.match(page, /ModelProvidersPanel/)
  assert.match(page, /ToolsAuthPanel/)
  assert.match(page, /query: \{ tab \}/)
  assert.match(toolsApi, /unwrapCredentialList/)
  assert.match(toolsApi, /default-credential/)
  assert.match(toolsApi, /deleteBuiltinCredential/)
})

test('datasets routes and top navigation mirror Dify knowledge module shell', () => {
  const router = readFileSync(new URL('../../../app/router/index.js', import.meta.url), 'utf8')
  const navigation = readFileSync(new URL('../../../app/navigation.js', import.meta.url), 'utf8')
  const list = readFileSync(new URL('../../datasets/pages/DatasetListPage.vue', import.meta.url), 'utf8')
  const wizard = readFileSync(new URL('../../datasets/pages/create/DatasetCreateWizard.vue', import.meta.url), 'utf8')
  const payload = readFileSync(new URL('../../datasets/model/createDocumentPayload.js', import.meta.url), 'utf8')
  const krPanel = readFileSync(new URL('../nodes/knowledge-retrieval/KnowledgeRetrievalPanel.vue', import.meta.url), 'utf8')
  const datasetsApi = readFileSync(new URL('../../datasets/api/difyDatasetsApi.js', import.meta.url), 'utf8')
  const docDetail = readFileSync(new URL('../../datasets/pages/documents/DocumentDetailPage.vue', import.meta.url), 'utf8')
  const hit = readFileSync(new URL('../../datasets/pages/hit-testing/HitTestingPage.vue', import.meta.url), 'utf8')
  const settings = readFileSync(new URL('../../datasets/pages/settings/DatasetSettingsPage.vue', import.meta.url), 'utf8')

  assert.match(router, /path: '\/datasets'/)
  assert.match(router, /datasets\/create/)
  assert.match(router, /hitTesting/)
  assert.match(router, /DocumentDetailPage/)
  assert.match(router, /HitTestingPage/)
  assert.match(router, /DatasetSettingsPage/)
  assert.match(navigation, /to: '\/datasets'/)
  assert.match(navigation, /label: '知识库'/)
  assert.match(list, /创建空知识库/)
  assert.match(wizard, /选择数据源/)
  assert.match(wizard, /createFirstDocument|\/datasets\/init/)
  assert.match(payload, /buildFileCreateDocumentPayload/)
  assert.match(krPanel, /to="\/datasets"/)
  assert.match(datasetsApi, /\/segments/)
  assert.match(datasetsApi, /segment\/enable/)
  assert.match(datasetsApi, /\/queries/)
  assert.match(datasetsApi, /external-knowledge-api/)
  assert.match(datasetsApi, /\/datasets\/external/)
  assert.match(datasetsApi, /website\/crawl/)
  assert.match(docDetail, /添加分段/)
  assert.match(hit, /召回测试/)
  assert.match(settings, /知识库设置/)
})

test('P3 external connect and datasource wizard panels exist', () => {
  const router = readFileSync(new URL('../../../app/router/index.js', import.meta.url), 'utf8')
  const connect = readFileSync(new URL('../../datasets/pages/connect/ConnectExternalKbPage.vue', import.meta.url), 'utf8')
  const notion = readFileSync(new URL('../../datasets/pages/create/sources/NotionSourcePanel.vue', import.meta.url), 'utf8')
  const web = readFileSync(new URL('../../datasets/pages/create/sources/WebsiteSourcePanel.vue', import.meta.url), 'utf8')
  const wizard = readFileSync(new URL('../../datasets/pages/create/DatasetCreateWizard.vue', import.meta.url), 'utf8')
  const dsAuth = readFileSync(new URL('../../datasets/api/difyDatasourceAuthApi.js', import.meta.url), 'utf8')
  const list = readFileSync(new URL('../../datasets/pages/DatasetListPage.vue', import.meta.url), 'utf8')

  assert.match(router, /ConnectExternalKbPage/)
  assert.match(connect, /createExternalKnowledgeBase/)
  assert.match(notion, /notion\/pre-import\/pages|fetchNotionPreImportPages/)
  assert.match(web, /createWebsiteCrawl|jinareader/)
  assert.match(wizard, /NotionSourcePanel/)
  assert.match(wizard, /WebsiteSourcePanel/)
  assert.match(wizard, /notion_import/)
  assert.match(dsAuth, /auth\/plugin\/datasource\/list/)
  assert.match(list, /goConnect/)
  assert.match(list, /连接外部知识库/)
})

test('P4 access / api / create-from-pipeline pages are wired', () => {
  const router = readFileSync(new URL('../../../app/router/index.js', import.meta.url), 'utf8')
  const access = readFileSync(new URL('../../datasets/pages/access-config/DatasetAccessConfigPage.vue', import.meta.url), 'utf8')
  const apiPage = readFileSync(new URL('../../datasets/pages/api/DatasetApiPage.vue', import.meta.url), 'utf8')
  const pipelineCreate = readFileSync(new URL('../../datasets/pages/create-from-pipeline/CreateFromPipelinePage.vue', import.meta.url), 'utf8')
  const accessApi = readFileSync(new URL('../../datasets/api/difyAccessControlApi.js', import.meta.url), 'utf8')
  const pipelineApi = readFileSync(new URL('../../datasets/api/difyPipelineApi.js', import.meta.url), 'utf8')
  const datasetsApi = readFileSync(new URL('../../datasets/api/difyDatasetsApi.js', import.meta.url), 'utf8')

  assert.match(router, /DatasetAccessConfigPage/)
  assert.match(router, /DatasetApiPage/)
  assert.match(router, /CreateFromPipelinePage/)
  assert.match(access, /updateDatasetOpenScope|permission/)
  assert.match(apiPage, /enableDatasetServiceApi|api-keys/)
  assert.match(pipelineCreate, /createPipelineDatasetFromYaml|从空白创建/)
  assert.match(accessApi, /rbac\/datasets/)
  assert.match(pipelineApi, /rag\/pipeline\/templates/)
  assert.match(datasetsApi, /api-keys\/enable/)
  assert.match(datasetsApi, /related-apps/)
})

test('P5 pipeline editor reuses WorkflowCanvas and draft APIs', () => {
  const router = readFileSync(new URL('../../../app/router/index.js', import.meta.url), 'utf8')
  const editor = readFileSync(new URL('../../datasets/pages/pipeline/PipelineEditorPage.vue', import.meta.url), 'utf8')
  const pipelineApi = readFileSync(new URL('../../datasets/api/difyPipelineApi.js', import.meta.url), 'utf8')
  const seed = readFileSync(new URL('../../datasets/model/pipelineTemplates.js', import.meta.url), 'utf8')

  assert.match(router, /PipelineEditorPage/)
  assert.match(editor, /WorkflowCanvas/)
  assert.match(editor, /savePipelineDraft/)
  assert.match(editor, /publishPipeline/)
  assert.match(editor, /useWorkflowDebugSession/)
  assert.match(editor, /runPipelineDraft/)
  assert.match(editor, /stopPipelineRun/)
  assert.match(editor, /flow-type="pipeline"/)
  assert.match(editor, /restorePipelineVersion/)
  assert.match(editor, /rag_pipeline_variables/)
  assert.match(editor, /transformDatasetToPipeline/)
  assert.match(pipelineApi, /\/workflows\/draft/)
  assert.match(pipelineApi, /\/workflows\/draft\/run/)
  assert.match(pipelineApi, /\/workflow-runs/)
  assert.match(pipelineApi, /node-executions/)
  assert.match(seed, /knowledge-index|KnowledgeBase/)

  const canvas = readFileSync(new URL('../canvas/WorkflowCanvas.vue', import.meta.url), 'utf8')
  assert.match(canvas, /flowType/)
  assert.match(canvas, /listPipelineRuns/)
  assert.match(canvas, /listPublishedPipelines/)
  assert.match(canvas, /startDraftPolling/)
  assert.match(canvas, /refreshChecklistIssues/)
  assert.match(canvas, /refreshActivePanelNode/)
  assert.match(canvas, /viewport-change-end/)
  assert.match(canvas, /never mutate node\.data/)
  assert.doesNotMatch(canvas, /watch\(workflowSignature/)
  assert.doesNotMatch(canvas, /const activePanelNode = computed/)
  assert.doesNotMatch(canvas, /const startVariables = computed/)
  assert.doesNotMatch(canvas, /fit-view-on-init/)
  assert.doesNotMatch(canvas, /data\._isBundled\s*=/)
})
test('canvas preserves integrations navigation without exposing it in the phase-one header', () => {
  const canvas = readFileSync(new URL('../canvas/WorkflowCanvas.vue', import.meta.url), 'utf8')
  const header = readFileSync(new URL('../canvas/components/WorkflowHeader.vue', import.meta.url), 'utf8')
  const selector = readFileSync(new URL('../nodes/shared/ModelSelector.vue', import.meta.url), 'utf8')
  const toolPanel = readFileSync(new URL('../nodes/tool/ToolPanel.vue', import.meta.url), 'utf8')

  assert.doesNotMatch(canvas, /ModelProviderSettings/)
  assert.match(canvas, /goToIntegrations/)
  assert.doesNotMatch(header, /integrations/)
  assert.doesNotMatch(header, /'publish'/)
  assert.doesNotMatch(header, /模型设置/)
  assert.match(selector, /\/integrations/)
  assert.match(toolPanel, /fetchBuiltinCredentials/)
  assert.match(toolPanel, /credentialId/)
  assert.match(toolPanel, /BuiltinToolCredentialDialog/)
  assert.doesNotMatch(toolPanel, /多凭证时填写 credential_id/)
})

test('workflow assist keeps the server optimistic-lock hash separate from the live draft revision', () => {
  const layout = readFileSync(new URL('../pages/WorkflowPage.vue', import.meta.url), 'utf8')
  const canvas = readFileSync(new URL('../canvas/WorkflowCanvas.vue', import.meta.url), 'utf8')
  const dock = readFileSync(new URL('../assistant/WorkflowAssistDock.vue', import.meta.url), 'utf8')

  assert.match(layout, /:draft-hash="workflowHash"/)
  assert.match(canvas, /:server-draft-hash="draftHash"/)
  assert.doesNotMatch(canvas, /:draft-hash="assistDraftRevision"/)
  assert.doesNotMatch(canvas, /:apply-hash="draftHash"/)
  assert.match(dock, /serverDraftHash/)
  assert.match(dock, /candidateStale/)
  assert.match(dock, /applyWorkflowAssistCandidate/)
})

test('selected workflow nodes expose a drag handle for Agent local editing', () => {
  const nodeControl = readFileSync(new URL('../nodes/base/NodeControl.vue', import.meta.url), 'utf8')

  assert.match(nodeControl, /draggable/)
  assert.match(nodeControl, /application\/x-workflow-assist-node/)
  assert.match(nodeControl, /handleAssistDragStart/)
})

test('Agent tool settings can create a builtin credential in place', () => {
  const section = readFileSync(new URL('../nodes/t/AgentToolsSection.vue', import.meta.url), 'utf8')

  assert.match(section, /BuiltinToolCredentialDialog/)
  assert.match(section, /openCredentialDialog/)
})

test('Agent composer accepts dropped workflow nodes as removable context chips', () => {
  const composer = readFileSync(new URL('../assistant/AssistComposer.vue', import.meta.url), 'utf8')

  assert.match(composer, /@drop/)
  assert.match(composer, /application\/x-workflow-assist-node/)
  assert.match(composer, /remove-target-node/)
})

test('v2 Assist composer does not restore planner resource chips or the resource browser', () => {
  const composer = readFileSync(new URL('../assistant/AssistComposer.vue', import.meta.url), 'utf8')
  const dock = readFileSync(new URL('../assistant/WorkflowAssistDock.vue', import.meta.url), 'utf8')

  assert.match(composer, /role="textbox"/)
  assert.match(composer, /@compositionstart/)
  assert.doesNotMatch(composer, /AssistSlashMenu/)
  assert.doesNotMatch(dock, /resourceBrowserOpen/)
  assert.doesNotMatch(dock, /AssistResourceBrowserDialog/)
})
